dist: trusty
language: node_js

node_js:
  - "8"
  - "6"

os:
  - linux
  - osx

addons:
  firefox: latest
  chrome: stable

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi

cache:
  yarn: true
  